#!/usr/bin/env bash

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ $HOME/.local/bin:$HOME/bin: ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

#install_sysext() {
#  SYSEXT="${1}"
#  URL="https://extensions.fcos.fr/extensions"
#  sudo install -d -m 0755 -o 0 -g 0 /etc/sysupdate.${SYSEXT}.d
#  sudo restorecon -RFv /etc/sysupdate.${SYSEXT}.d
#  curl --silent --fail --location "${URL}/${SYSEXT}.conf" \
#    | sudo tee "/etc/sysupdate.${SYSEXT}.d/${SYSEXT}.conf"
#  sudo /usr/lib/systemd/systemd-sysupdate update --component "${SYSEXT}"
#}

#uninstall_sysext() {
#  SYSEXT="${1}"
#  sudo rm -i "/var/lib/extensions/${SYSEXT}.raw"
#  sudo rm -i "/var/lib/extensions.d/${SYSEXT}-"*".raw"
#  sudo rm -i "/etc/sysupdate.${SYSEXT}.d/${SYSEXT}.conf"
#  sudo rmdir "/etc/sysupdate.${SYSEXT}.d/"
#}

#update_sysext() {
#for c in $(/usr/lib/systemd/systemd-sysupdate components --json=short | jq --raw-output '.components[]'); do
#    sudo /usr/lib/systemd/systemd-sysupdate update --component "${c}"
#done
#}

#export PATH="$PATH:~/.cargo/bin"
# xremap bash completion
#eval "$(xremap --completions bash)"
# aliases
alias cls=clear
alias ff=fastfetch
#alias steam="flatpak run com.valvesoftware.Steam"

function fup {
sh "$HOME/.flatpak/flatpak-sync-backup-gen.sh"
chezmoi re-add "$HOME/.flatpak/flatpak-sync-backup.sh"
}

function fed {
nano "$HOME/.flatpak/flatpak-sync-backup-gen.sh"
chezmoi re-add "$HOME/.flatpak/flatpak-sync-backup-gen.sh"
}

alias fin="sh ~/.flatpak/flatpak-sync-backup.sh"
#alias frep="sh ~/.flatpak/remove-fedora-repo.sh"

function rced {
nano "$HOME/.bashrc"
chezmoi re-add "$HOME/.bashrc"
source "$HOME/.bashrc"
}

alias cz=chezmoi
alias cra="chezmoi re-add"
alias cza="chezmoi add"
alias la="ls -al"
alias ll="ls -al"

function gup {
git add .
git commit -m "update"
git push
}

function nup {
cd "$HOME/nixos-config"
gup
cd "/etc/nixos"
sudo git pull
}
alias nano=vim
#alias rdext="sudo systemctl restart systemd-sysext.service"
#alias sensors="nix-shell --run sensors"
