#!/usr/bin/env bash
# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ $HOME/.local/bin:$HOME/bin: ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

. /run/current-system/sw/share/bash-completion/bash_completion

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

alias cls=clear
alias ff=fastfetch


function rced {
nano "$HOME/.bashrc"
chezmoi re-add "$HOME/.bashrc"
source "$HOME/.bashrc"
}

alias cz=chezmoi
alias cra="chezmoi re-add"
alias cza="chezmoi add"
alias la="ls -al"
alias ll="ls -al"

function gup {
git add .
git commit -m "update"
git push
}

function nup {
cd "$HOME/finix-config" || return
gup
}
function nrs {
nup
sudo nixos-rebuild switch --flake "$HOME/finix-config" --option access-tokens github.com="$(gh auth token)"
nup
}
function nrb {
nup
sudo nixos-rebuild boot --flake "$HOME/finix-config" --option access-tokens github.com="$(gh auth token)"
nup
}
function nfu {
nup
cd "$HOME/finix-config" || return
nix flake update --option access-tokens github.com="$(gh auth token)"
nup
}

function batfix {
echo "Modify the start threshold of BAT1"
sudoedit /sys/class/power_supply/BAT1/charge_control_start_threshold
echo "/sys/class/power_supply/BAT1/charge_control_start_threshold" = "$(cat /sys/class/power_supply/BAT1/charge_control_start_threshold)"

echo "Modify the stop threshold of BAT1"
sudoedit /sys/class/power_supply/BAT1/charge_control_end_threshold
echo "/sys/class/power_supply/BAT1/charge_control_end_threshold" = "$(cat /sys/class/power_supply/BAT1/charge_control_end_threshold)"

echo "Modify the start threshold of BAT2"
sudoedit /sys/class/power_supply/BAT2/charge_control_start_threshold
echo "/sys/class/power_supply/BAT2/charge_control_start_threshold" = "$(cat /sys/class/power_supply/BAT2/charge_control_start_threshold)"

echo "Modify the stop threshold of BAT2"
sudoedit /sys/class/power_supply/BAT2/charge_control_end_threshold
echo "/sys/class/power_supply/BAT2/charge_control_end_threshold" = "$(cat /sys/class/power_supply/BAT2/charge_control_end_threshold)"
}

function ngc {
	sudo nix-collect-garbage -d
	sudo nix-collect-garbage
	nrs
}

alias zzz="sudo zzz"
alias poweroff="sudo poweroff"
alias reboot="sudo reboot"
. /run/current-system/sw/share/blesh/ble.sh 
