flatpak install flathub com.google.Chrome -y
flatpak install flathub io.github.celluloid_player.Celluloid -y
flatpak install fedora org.fedoraproject.MediaWriter -y
flatpak install fedora org.gnome.Calculator -y
flatpak install fedora org.gnome.Calendar -y
flatpak install fedora org.gnome.Characters -y
flatpak install fedora org.gnome.Connections -y
flatpak install fedora org.gnome.Contacts -y
flatpak install fedora org.gnome.Evince -y
flatpak install fedora org.gnome.Extensions -y
flatpak install flathub org.gnome.Geary -y
flatpak install fedora org.gnome.Logs -y
flatpak install fedora org.gnome.Loupe -y
flatpak install fedora org.gnome.Maps -y
flatpak install fedora org.gnome.NautilusPreviewer -y
flatpak install fedora org.gnome.Snapshot -y
flatpak install fedora org.gnome.TextEditor -y
flatpak install fedora org.gnome.Weather -y
flatpak install fedora org.gnome.baobab -y
flatpak install fedora org.gnome.clocks -y
flatpak install fedora org.gnome.font-viewer -y
flatpak install fedora org.gnome.seahorse.Application -y
flatpak install flathub org.keepassxc.KeePassXC -y
flatpak install flathub org.telegram.desktop -y
