flatpak install flathub ca.desrt.dconf-editor -y
flatpak install flathub ca.desrt.dconf_editor.Locale -y
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub com.google.Chrome -y
flatpak install flathub com.mattjakeman.ExtensionManager -y
flatpak install flathub com.mattjakeman.ExtensionManager.Locale -y
flatpak install flathub io.github.amit9838.mousam -y
flatpak install flathub io.github.amit9838.mousam.Locale -y
flatpak install flathub io.github.celluloid_player.Celluloid -y
flatpak install flathub io.github.celluloid_player.Celluloid.Locale -y
flatpak install flathub io.github.dvlv.boxbuddyrs -y
flatpak install flathub io.github.dvlv.boxbuddyrs.Locale -y
flatpak install flathub org.freedesktop.Platform -y
flatpak install flathub org.freedesktop.Platform -y
flatpak install flathub org.freedesktop.Platform.GL.default -y
flatpak install flathub org.freedesktop.Platform.GL.default -y
flatpak install flathub org.freedesktop.Platform.GL.default -y
flatpak install flathub org.freedesktop.Platform.GL.default -y
flatpak install flathub org.freedesktop.Platform.Locale -y
flatpak install flathub org.freedesktop.Platform.Locale -y
flatpak install flathub org.freedesktop.Platform.VAAPI.Intel -y
flatpak install flathub org.freedesktop.Platform.VAAPI.Intel -y
flatpak install flathub org.freedesktop.Platform.ffmpeg-full -y
flatpak install flathub org.gnome.Calculator -y
flatpak install flathub org.gnome.Calculator.Locale -y
flatpak install flathub org.gnome.Calendar -y
flatpak install flathub org.gnome.Calendar.Locale -y
flatpak install flathub org.gnome.Characters -y
flatpak install flathub org.gnome.Characters.Locale -y
flatpak install flathub org.gnome.Connections -y
flatpak install flathub org.gnome.Connections.Locale -y
flatpak install flathub org.gnome.Contacts -y
flatpak install flathub org.gnome.Contacts.Locale -y
flatpak install flathub org.gnome.Evince -y
flatpak install flathub org.gnome.Evince.Locale -y
flatpak install flathub org.gnome.Extensions -y
flatpak install flathub org.gnome.Extensions.Locale -y
flatpak install flathub org.gnome.Firmware -y
flatpak install flathub org.gnome.Firmware.Locale -y
flatpak install flathub org.gnome.Geary -y
flatpak install flathub org.gnome.Geary.Locale -y
flatpak install flathub org.gnome.Logs -y
flatpak install flathub org.gnome.Logs.Locale -y
flatpak install flathub org.gnome.Loupe -y
flatpak install flathub org.gnome.Loupe.Locale -y
flatpak install flathub org.gnome.Maps -y
flatpak install flathub org.gnome.Maps.Locale -y
flatpak install flathub org.gnome.NautilusPreviewer -y
flatpak install flathub org.gnome.NautilusPreviewer.Locale -y
flatpak install flathub org.gnome.Platform -y
flatpak install flathub org.gnome.Platform -y
flatpak install flathub org.gnome.Platform.Locale -y
flatpak install flathub org.gnome.Platform.Locale -y
flatpak install flathub org.gnome.Snapshot -y
flatpak install flathub org.gnome.Snapshot.Locale -y
flatpak install flathub org.gnome.TextEditor -y
flatpak install flathub org.gnome.TextEditor.Locale -y
flatpak install flathub org.gnome.baobab -y
flatpak install flathub org.gnome.baobab.Locale -y
flatpak install flathub org.gnome.clocks -y
flatpak install flathub org.gnome.clocks.Locale -y
flatpak install flathub org.gnome.font-viewer -y
flatpak install flathub org.gnome.font_viewer.Locale -y
flatpak install flathub org.gnome.seahorse.Application -y
flatpak install flathub org.gnome.seahorse.Application.Locale -y
flatpak install flathub org.gtk.Gtk3theme.Adwaita-dark -y
flatpak install flathub org.kde.KStyle.Adwaita -y
flatpak install flathub org.kde.Platform -y
flatpak install flathub org.kde.Platform.Locale -y
flatpak install flathub org.kde.PlatformTheme.QGnomePlatform -y
flatpak install flathub org.kde.WaylandDecoration.QAdwaitaDecorations -y
flatpak install flathub org.keepassxc.KeePassXC -y
flatpak install flathub org.libreoffice.LibreOffice -y
flatpak install flathub org.libreoffice.LibreOffice.Locale -y
flatpak install flathub org.telegram.desktop -y
flatpak install flathub org.telegram.desktop.webview -y
flatpak install flathub org.vinegarhq.Sober -y
flatpak install flathub xyz.xclicker.xclicker -y
